# Site settings
name: zcybupt
email: zcybupt2016@hotmail.com
author: Chunyu Zhao
url: https://zcybupt.github.io
# resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/zcybupt
baseurl: ""
description: less is more!
meta_description: Test;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zcybupt

# Build settings
markdown: kramdown

baidu_analysis: 8108f369ee3a154c180974606d5973c5

